= Conda OpenHPC RPM

This repository provides the `spec` file and patches needed to build an RPM suitable for installing `conda` on an OpenHPC system. https://docs.conda.io/en/latest/[Conda] is an open source package manager and environment manager primarily (but not exclusively) used for managing Python environments and installations. Conda is usually distributed as part of https://anaconda.org/[Anaconda] or https://docs.conda.io/en/latest/miniconda.html[Miniconda]. However, the `conda-ohpc` RPM is specifically written to seamlessly incorporate the Conda package and environment manager into an https://openhpc.community/[OpenHPC] managed cluster.

== Building the `conda-ohpc` RPM

To simplify building the RPM for OpenHPC, we will use https://github.com/rpm-software-management/mock[Mock], a chroot build environment manager, and the Mock Config files found in the https://gitlab.trecis.cloud/infrastructure/packages/conda-openhpc[TRECIS OpenHPC Build Helpers repository]. To get started, follow the getting started with OpenHPC and Mock documentation.

// TO DO: Actually write the above documentation

NOTE: The following documentation will use the variables `$OHPC_CFG`, to refer to your selected OpenHPC Mock configuration, `$SPEC`, to refer to the path to the `conda-ohpc` spec file (typically in the `SPEC` directory), and `$SRPM`, to refer to the source RPM.

=== Building the `conda-ohpc` SRPM

Mock works by building an existing source RPM (SRPM). To build the SRPM, run the following command from the root directory of this project:

```bash
rpmbuild -bs --define="_topdir $PWD" $SPEC
```

This will build an `SRPM` in the `SRPMS` directory, relative to the root of this project. Next, we use Mock to create a clean build environment and build the final RPM. In the root directory of this project, run:

```bash
mock -r $OHPC_CFG --resultdir RPMS/ $SRPM
```

If all goes well, this will result in an RPM in the `RPMS` directory called something like `conda-ohpc-4.11.0-1.ohpc.2.0.0.x86_64.rpm` depending on the architecture you built for and the conda version.