= Python OpenHPC RPM

This repository provides the `spec` file and patches needed to build an RPM 
suitable for installing `python` on an OpenHPC system. 

== Building the `python<version>-<compiler>-ohpc` RPM

To simplify building the RPM for OpenHPC, we use 
https://github.com/rpm-software-management/mock[Mock], a chroot build 
environment manager, and the Mock Config files found in the 
https://gitlab.trecis.cloud/infrastructure/packages/conda-openhpc[TRECIS OpenHPC
Build Helpers repository]. 
To get started, follow the getting started with OpenHPC and Mock documentation.

// TO DO: Actually write the above documentation

NOTE: The following documentation will use the variables `$OHPC_CFG`, to refer 
to your selected OpenHPC Mock configuration, `$SPEC`, to refer to the path to 
the `mamba` spec file (typically in the `SPEC` directory), and 
`$SRPM`, to refer to the source RPM.

=== Building the `python<version>-<compiler>-ohpc` SRPM

Mock works by building an existing source RPM (SRPM). To build the SRPM, run the
following command from the root directory of this project:

```bash
rpmbuild -bs --define="_topdir $PWD" \
  --define="OHPC_COMPILER_FAMILY <desired compiler family>" \
  SPECS/python.spec
```

This will build an `SRPM` in the `SRPMS` directory, relative to the root of this
project. Next, we use Mock to create a clean build environment and build the 
final RPM. In the root directory of this project, run:

```bash
mock -r $OHPC_CFG --resultdir RPMS/  $SRPM
```

If all goes well, this will result in an RPM in the `RPMS` directory called 
something like `python38-gnu9-ohpc-3.8.14-1.ohpc.2.0.0.x86_64.rpm` depending 
on the architecture you built for, the compiler version, and the python version.
